### ISSUE TITLE
当为文件添加自定义数据时，如果关键字使用了下划线"_"就会上传失败！

### ISSUE THREAD

**Issue by billschen** [aliyun/aliyun-oss-csharp-sdk#11]
如题，我在C#使用了类似：
`metadata.UserMetadata.Add("share_in", "abcd");`
的代码，出现错误：The request signature we calculated does not match the signature you provided. Check your key and signing method.
不要就没事。

**Comment by baiyubin** [comment]
您好，可以使用“-”代替“_”吗？

**Comment by billschen** [comment]
没有说可不可以，如其使用 “-” 不如不用。
因为我的 Metadata 用户通过web指定的，通过mvc程序中的model传过来。
我没有办法写一个如：
class{
   public string share-in {get;set;}
}
的类吧？
我好奇的是：为什么不能用 ？

**Comment by huiguangjun** [comment]
不支持header 中 使用 _
