### ISSUE TITLE
2.10.0 不支持 .net 3.5/4.0 了吗？

### ISSUE THREAD

**Issue by qiu-xm** [aliyun/aliyun-oss-csharp-sdk#110]
![QQ截图20200630105311](https://user-images.githubusercontent.com/1689901/86078100-eb742a00-babf-11ea-9e02-fe4aef0df755.png)

**Comment by qiu-xm** [comment]
下载缩略图的问题依然存在。。。（缩略图是由oss自动生成的）
image/edd832fbfba9c509bb021ec86a5c1507_middle

Aliyun.OSS.Common.ClientException: Expected hash not equal to calculated hash
   在 Aliyun.OSS.Common.Internal.HashStream.CalculateHash()
   在 Aliyun.OSS.Common.Internal.HashStream.Close()
   在 System.IO.Stream.Dispose()

**Comment by huiguangjun** [comment]
下个版本兼容 3.5/4.0
