### ISSUE TITLE
BeginPutObject有一个明显的bug，至少和PutObject行为上不一致,懒得提交PR了，希望有人看到了改一下子

### ISSUE THREAD

**Issue by ipoetry** [aliyun/aliyun-oss-csharp-sdk#117]
PutObject ：

![image](https://user-images.githubusercontent.com/11779890/92563826-c6174f80-f2aa-11ea-9a61-79a78c5cb176.png)

BeginPutObject:
![image](https://user-images.githubusercontent.com/11779890/92563859-d6c7c580-f2aa-11ea-9e79-64ff87f93978.png)
缺少putObjectRequest.Metadata = metadata; 导致我使用异步时，必须显式的创建一个ObjectMetadata,否则自动识别Content-Type不会生效。

**Comment by huiguangjun** [comment]
谢谢反馈, 已经修改,
