### ISSUE TITLE
私有bucket在URL中包含签名问题

### ISSUE THREAD

**Issue by checkme5** [aliyun/aliyun-oss-csharp-sdk#3]
https://help.aliyun.com/document_detail/oss/api-reference/access-control/signature-url.html?spm=5176.docoss/oss-img-guide/access/signature.2.9.e3B1jt

按照文档中的描述，在一个私有的bucket中拼装出一个自定义的带style的Resource（object@!60w60h）
得到的url总是报The request signature we calculated does not match the signature you provided. Check your key and signing method.错误。

不知道有没有人碰到过这个问题。

**Comment by checkme5** [comment]
还有一个问题是，默认的SDK生成的Signature=tAjmj+++YB6KLvO6yjS9LY3uzc4=这里面包涵特殊的url字符，这个问题。oss的服务端是怎么样处理的呢？

**Comment by qiyuewuyi** [comment]
1，你是使用sdk时报签名错误还是你自己实现签名的时候会报签名错误？
2，发送方url encode，接收方url decode

**Comment by checkme5** [comment]
我用的SDK里面的方法GeneratePresignedUri。

**Comment by checkme5** [comment]
GeneratePresignedUri方法不好用，提交工单后说去掉bucket参数，然后我拼成了如下字符串。
canonicalString = "GET\n\n\n1452678020\nxxxxxxxxxxxxxxxxxxxx.jpg@!60w60h"
加密后得到的结果还是SignatureDoesNotMatch。

**Comment by checkme5** [comment]
GeneratePresignedUri中的Date参数和
https://help.aliyun.com/knowledge_detail/5994379.html?spm=5176.788315694.2.7.NOKUQM
描述的实现不一样。

**Comment by qiyuewuyi** [comment]
没理解你为啥要自己拼接canonicalString? 使用GeneratePresignedUri时，按理是不需要你拼接字符串，你只需要提供bucketname，object key和一些其他meta信息就可以了。你可以看看这个示例：https://github.com/aliyun/aliyun-oss-csharp-sdk/blob/master/samples/Samples/UrlSignatureSample.cs ，另外可以看一下测试部分的UrlSignature相关的。
如果我理解不对，你可以说一下你使用方式或者贴一下相关代码

**Comment by checkme5** [comment]
按GeneratePresignedUri里的实现，传的参数生成的url传递到oss提示的就是SignatureDoesNotMatch。

**Comment by qiyuewuyi** [comment]
上面链接里面的sample运行的时候，也是提示这个错误吗？

**Comment by qiyuewuyi** [comment]
我这边用你的key，测试了下是没问题的。你可以贴一下你的配置看看

**Comment by checkme5** [comment]
是的用sample里运行，如果带style就会报错。

**Comment by qiyuewuyi** [comment]
这里沟通效率不好。你可以提个工单，或者直接旺旺加群：1421921057。这样能更快解决你的问题。

**Comment by likan971** [comment]
如果需要直接在浏览器访问，请使用GeneratePresignedUri方法返回Uri中的AbsoluteUri属性。
