### ISSUE TITLE
为何Resumable只有上传，没下载

### ISSUE THREAD

**Issue by a44281071** [aliyun/aliyun-oss-csharp-sdk#4]
写一个呗？要不然光有上传，没下载就很心碎了，毕竟全文件获取也是有机会用的。

**Comment by qiyuewuyi** [comment]
你可以先参考这个：https://github.com/aliyun/aliyun-oss-csharp-sdk/blob/master/samples/Samples/GetObjectByRangeSample.cs 。

ResumableDownload接口的实现和上面的示例程序应该差不多，也要通过GetRange实现。

**Comment by huiguangjun** [comment]
新版本已经提供resume down 接口。
