### ISSUE TITLE
Aliyun.OSS.OssClient.DoesObjectExist 报 NullReferenceException 异常，为什么？

### ISSUE THREAD

**Issue by qiu-xm** [aliyun/aliyun-oss-csharp-sdk#59]
Aliyun.OSS.dll 版本：2.5.1.0 【升级 aliyun_oss_dotnet_sdk_2_8_0 后一样】
OSVersion:Microsoft Windows NT 6.2.9200.0 NetFrameworkVersion:4.0.30319.42000

System.NullReferenceException: 未将对象引用设置到对象的实例。
   **在 Aliyun.OSS.OssClient.DoesObjectExist(String bucketName, String key)**
   在 xxxx.UploadAliyunOSSImage()

完全没有头绪

**Comment by huiguangjun** [comment]
请参考 sample 里的  DoesObjectExistSample.DoesObjectExist(bucketName);
 使用方法
