### ISSUE TITLE
dotnet core 2.1报错

### ISSUE THREAD

**Issue by sgyy** [aliyun/aliyun-oss-csharp-sdk#66]
再dotnet core 2.0 下运行正常
dotnet core 2.1报错
错误信息如下：

` The stream was already consumed. It cannot be read again.`

```
   at System.Net.Http.HttpConnection.HttpConnectionResponseContent.ConsumeStream()
   at System.Net.Http.HttpConnection.HttpConnectionResponseContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.CopyToAsyncCore(ValueTask copyTask)
```

**Comment by zousq19910623** [comment]
你好，请教下，master分支支持.net core 2.0了是吗？

**Comment by liguobao** [comment]
看了下最新版是基于4.6.1的.

Error: Package 'Aliyun.OSS.SDK 2.9.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.

**Comment by liguobao** [comment]
刚刚试了一下,可以使用 <PackageReference Include="Aliyun.OSS.SDK.NetCore" Version="2.9.0"/>

dotnet core 2.1 正常.

**Comment by BrisWhite** [comment]
.NetCore 2.1环境下：
![image](https://user-images.githubusercontent.com/5007541/50372576-e5200a80-060b-11e9-8ef4-47cb84c9a3b0.png)

.NetCore 2.0环境下：
![image](https://user-images.githubusercontent.com/5007541/50372582-f8cb7100-060b-11e9-8b7a-8fdfac09242d.png)

![image](https://user-images.githubusercontent.com/5007541/50372616-a9397500-060c-11e9-88f6-205601e16d9f.png)
System.Net.Http.HttpConnection.HttpConnectionResponseContent的流无法读取两次。

**Comment by rujianwang** [comment]
请问下 这个bug修复了吗？

**Comment by caopengfei** [comment]
至今都没修复，没人管的

**Comment by caopengfei** [comment]
你可以下载源码调试下你的代码，找到阿里云的自定义错误，只要解决了自定义错误的问题，代码就不会走到这个错误分支来了。也就是只有你传递的参数，或者授权权限有问题的时候，才会进入这段代码，我就是因为出现了权限错误（403），所以报错的，发现是少了传了一个参数(demo里面也没传)

**Comment by huiguangjun** [comment]
已更新到master 分支
