### ISSUE TITLE
2.9版什么时候发布到nuget啊？

### ISSUE THREAD

**Issue by linys2333** [aliyun/aliyun-oss-csharp-sdk#74]
nuget一直都是2.8版，而2.9版才支持.net core2。。。

**Comment by huiguangjun** [comment]
2.9 版本已经发布，请在nuget上搜索 aliyun.oss.sdk.netcore, 然后下载安装

**Comment by linys2333** [comment]
@huiguangjun 安装了nuget包，发现目标框架是用的.netframework？
![360 20180919172622379](https://user-images.githubusercontent.com/22143693/45744580-79578b80-bc31-11e8-8aef-5a2f4f626720.jpg)
