### ISSUE TITLE
匹配ContentType时要大小写不敏感

### ISSUE THREAD

**Issue by qiangchong2017** [aliyun/aliyun-oss-csharp-sdk#77]
在上传文件到OSS时，若文件的后缀名是大写的，则匹配ContentType是为二进制流了，这个需要不区分大小写
HttpUtils.cs的第118行代码：
原代码为：fileType = fileType.Trim().TrimStart(new char[1] { '.' })
修改为：fileType = fileType.Trim().TrimStart(new char[1] { '.' }).ToLower();

即可实现上述的需求

**Comment by huiguangjun** [comment]
谢谢您的反馈，在后续的版本会兼容这个场景。

**Comment by huiguangjun** [comment]
已经修改到 fixbug分支，
