### ISSUE TITLE
图片处理持久化

### ISSUE THREAD

**Issue by knat** [aliyun/aliyun-oss-csharp-sdk#86]
Java SDK https://help.aliyun.com/document_detail/47505.html?spm=a2c4g.11186623.2.15.4301cb462mqZMy#section-rqc-yfd-lfb
有ProcessObjectRequest对象，.NET SDK没有？该怎么做？谢谢

**Comment by huiguangjun** [comment]
下个版本会补齐该功能。
你也可以先参考这个文档https://help.aliyun.com/document_detail/55811.html?spm=a2c4g.11186623.6.1286.62151717lEE32F，对net sdk的源码做修改。

**Comment by itsvse** [comment]
增加图片持久化功能 [https://github.com/itsvse/aliyun-oss-csharp-sdk](https://github.com/itsvse/aliyun-oss-csharp-sdk)

**Comment by huiguangjun** [comment]
2.13.0 已支持
