### ISSUE TITLE
when endpoint or bucket name is invalid, got Ojbect reference not set ... error

### ISSUE THREAD

**Issue by sw0** [aliyun/aliyun-oss-csharp-sdk#89]
Project Type: .NET Core (2.2)
Referenced Nuget package: Aliyun.OSS.SDK v2.9.0

Got exception when endpoint is invalid.
```
System.NullReferenceException: 'Object reference not set to an instance of an object.'
```

**Comment by sw0** [comment]
I found I was using incorrect package, the one for .NET Framework, not for .NET Core.

**Comment by Gavinluo** [comment]
same to you
