### ISSUE TITLE
有支持.net core的计划么

### ISSUE THREAD

**Issue by zzs89117920** [aliyun/aliyun-oss-csharp-sdk#9]
有支持.net core的计划么

**Comment by baiyubin** [comment]
目前.net sdk尚不支持.net core，该需求我们需要先调研排期，然后才能给出计划。感谢您的反馈，计划将在后继给出，请您持续关注。

**Comment by codeice** [comment]
检测bucket是否存在，为嘛我随便传入一个bucket名字都返回true额。。。。

**Comment by codeice** [comment]
![image](https://cloud.githubusercontent.com/assets/6001799/17797449/9081491a-65fb-11e6-854a-117165c9159c.png)

实际上已经有的bucket:
![image](https://cloud.githubusercontent.com/assets/6001799/17797456/a1bbe91a-65fb-11e6-86c2-5263211d9a7e.png)

**Comment by leshin** [comment]
希望赶紧推出.net core版本，现在就因为这个，搞得不能在Linux上跑。

**Comment by zhang1yun1** [comment]
附议，希望能出.net core版本

**Comment by baiyubin** [comment]
在linux可以使用Mono，详细请参考官方文档 https://help.aliyun.com/document_detail/32086.html。

**Comment by zhang1yun1** [comment]
mono性能很低的。
使用.net core是看中它的高性能和微软官方支持。
我们实际测试显示.net core的吞吐量明显高于nodejs和go，mono就更不用说了。
.net core是.net未来的趋势了，希望能尽快推出.net core版本。

**Comment by Henxi** [comment]
net core还不支持，要加把劲啊，希望能尽快推出.net core版本。

**Comment by kencery** [comment]
什么时候能支持Core呢？坐等呢~~~~

**Comment by zhougangnj** [comment]
2017年了，什么时候支持core啊

**Comment by kencery** [comment]
@zhougangnj  可以用七牛，已经支持了~

**Comment by Henxi** [comment]
马云，你妈妈叫你回家写.NET CORE SDK.

**Comment by baiyubin** [comment]
@codeice，您好，Bucket `23233` 是存在的，是其它用户的Bucket。 DoesBucketExist的含义是所有用户下指定的bucket是否存在。

**Comment by cuiliang** [comment]
开源一个dotnet core 的版本
https://github.com/cuiliang/Cuiliang.AliyunOssSdk
nuget：https://www.nuget.org/packages/Cuiliang.AliyunOssSdk/

**Comment by DeyiXu** [comment]
程序都写好了，就差你们的这个.net core版本的SDK了！

**Comment by Henxi** [comment]
阿里云垃圾，如果有用使用阿里云RDS的同学要注意随时被扣费（包括预付费产品）。
RDS数据库备份强制收费，还不能关闭功能，反馈过去，阿里云的人员三次承认产品逻辑有问题，但是不承认是自己错误，态度叼叼的。

价值观不符合，浪费了我1万多块，已经放弃阿里云，改用腾讯云。

类似的问题，2016年就有人反馈过：
https://bbs.aliyun.com/read/273020.html?pos=4

**Comment by cyroby** [comment]
希望能出.net core版本

**Comment by hubluesky** [comment]
@baiyubin 亲爱的亲，Mono的这个链接打不开，是否有其它链接。

**Comment by www2sssyyy** [comment]
@kencery 这就去七牛

**Comment by dbsquared** [comment]
同求!!!

**Comment by qixu001** [comment]
我们已经在实现了，请耐心等候。
关于.net core的版本，大家有什么建议？ 2.0今年已经出来了，感觉提高很大。

**Comment by DeyiXu** [comment]
@qixu001  支持 👍

**Comment by RainingNight** [comment]
@qixu001 支持支持。

**Comment by dbsquared** [comment]
@qixu001 加油!!!
多嘴问句,大概2018年初可以发布吗?

**Comment by qixu001** [comment]
net-core分支里有我们正在开发的dotnetcore的支持。单元测试已经跑过了，只是我们还没有做过很详细的测试，不建议用在生产环境中。有兴趣的话你们可以测试一下，有问题请反馈，多谢

**Comment by witskeeper** [comment]
是否可以考虑支持为.net standard 2.0

**Comment by RainingNight** [comment]
any news ? :)

**Comment by qixu001** [comment]
The branch net-core is the .net core support branch----it's pending the code review, but it passed all unit tests.
If you're interested, please try it out. For now, it's not recommended in prod environment as the code review is not done yet.

**Comment by qixu001** [comment]
嗯， .net core 2.0支持 .net standard 2.0 标准

**Comment by dbsquared** [comment]
@qixu001 方便的话,.net core 的分支能不能给个安装教程,也方便大家在发布前做测试,毕竟是直接下源代码手动安装,感觉要趟点坑啊

**Comment by RainingNight** [comment]
开工了，，，，进展如何了？

**Comment by qixu001** [comment]
@RainingNight 目前正在Review和测试。如果有更新会在这里通知大家。
如果你想先行试用的话，目前net-core分支可以拿来作为测试用途。谢谢。

**Comment by RainingNight** [comment]
月底要发布，能上生产不？？

**Comment by xl-wenqiang** [comment]
还没发布？

**Comment by xl-wenqiang** [comment]
看了下，发现七牛云支持.NET Core，而且注册就有免费空间，挺方便开发和调测的。

**Comment by RainingNight** [comment]
@xl-wenqiang 是啊，七牛支持的挺好，这个有点墨迹，但是主机用的阿里，可以走内网。

**Comment by dbsquared** [comment]
还没发布,这都什么时候了.

**Comment by night-king** [comment]
附议，希望能出.net core版本

**Comment by KarlHuang0509** [comment]
建议先推一个 .net core 预览版

**Comment by zengqinglei** [comment]
这个是真的慢，，我们都2.1了，生产上了好几个项目，就这个等了快一年，还没.net core

**Comment by RainingNight** [comment]
不等了，已上七牛。。。

**Comment by qixu001** [comment]
最新的master版本已经有.net core了。

**Comment by zzs89117920** [comment]
@qixu001  希望2.9版本尽快发布

**Comment by dbsquared** [comment]
已经转AWS了,拖延症等不起啊.

**Comment by huiguangjun** [comment]
2.9.0 版本上已经支持
